apiVersion: ai.sap.com/v1alpha1
kind: Scenario
metadata:
  name: st22-ai
spec:
  description: "ST22 Dump Analysis AI Scenario"
  # version you want to register
  version: "1.0.0"
  executables:
    - name: st22-ai-workflow
      type: workflow
